name: docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag shadimd/shadi-mohammad-devops:${{ github.run_number }}-${{ github.sha }}

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Push Docker Image to Registry
        run: docker push shadimd/shadi-mohammad-devops:${{ github.run_number }}-${{ github.sha }}
